name: Build Docker Image (hugface)

on:  
  push:
    branches:
      - hug
    paths-ignore:
      - 'README.md'
      - 'docker-compose.yml'
      - 'docker-compose-warp.yml'
      - 'docs/**'
      - '.github/workflows/build_docker_hug.yml'
  workflow_dispatch:

jobs:
  hugface:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Read the version from version.txt
        id: get_version
        run: |
          version=$(cat version.txt)
          echo "Current version: v$version"
          echo "::set-output name=version::v$version"      

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3      

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/hg_c2a
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ steps.get_version.outputs.version }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max     
